### ISSUE TITLE
Sync data to Elastic Search via ABC would hit error when delete or edit data in PostgreSQL

### ISSUE THREAD

**Issue by Amber-1111** [appbaseio/abc#122]
abc version
Version:        0.6.6
Variant:         !oss
Go version:   go1.9
OS:               windows
Arch:            amd64

Hi, I've been successfully using ABC to sync data to ES when insert a record, but the error shows when delete or edit data. 
←[31mERRO←[0m[0015] elastic: Error 400 (Bad Request): Validation Failed: 1: id is missing;[type=action_request_validation_exception]  ←[31mversion←[0m=5 ←[31mwriter←[0m=elasticsearch

And btw, does ABC support sync DB views with Elastic Search?

##### Checks

- [x] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [x] This issue has a description.

**Comment by utsavoza** [comment]
Hello Amber, in order to tail the changes in postgres db we need to explicitly provide `_id` for the doc that gets indexed to elasticsearch, otherwise it will be autogenerated and the next time we want to update or delete that doc we would not have its `_id` to do so and we would subsequently encounter the error you did above. One solution would be to use the `rename` transform function that `abc` provides. For example, for a postgres relation we would be indexing individual rows as separate docs in elasticsearch, and it would be preferrable to use the PRIMARY KEY for the relation as the doc `_id`. I believe, the transform file, assuming `transform_file.js`, would look something like this: 
```
t.Source("source", source, "/.*/")
  .Transform(rename({ field_map: { <primary_key_field>: "_id" } }))
  .Save("sink", sink, "/.*/");
```   
and using the same transform file, the abc command would look something like: 
```abc import --src_type=postgres --src_uri="postgresql://<user>:<password>@localhost:5432/<db>" --transform_file="transform_file.js" "https://USER:PASS@scalr.api.appbase.io/abcpostgrestest"```

If you need more help regarding transforms, check out [this](https://github.com/appbaseio/abc/tree/dev/docs/importer/transforms) link.
